sudo: false
language: python
cache:
  pip: true
  directories:
  - $TRAVIS_BUILD_DIR/.tox
matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py27-dj111
    python: 2.7
  - env: TOX_ENV=py34-dj111
    python: 3.4
  - env: TOX_ENV=py35-dj111
    python: 3.5
  - env: TOX_ENV=py36-dj111
    python: 3.6
  - env: TOX_ENV=py34-dj20
    python: 3.4
  - env: TOX_ENV=py35-dj20
    python: 3.5
  - env: TOX_ENV=py36-dj20
    python: 3.6
  - env: TOX_ENV=py37-dj20
    sudo: true  # TODO Remove when supported
    dist: xenial
    python: 3.7
  - env: TOX_ENV=py35-dj21
    python: 3.5
  - env: TOX_ENV=py36-dj21
    python: 3.6
  - env: TOX_ENV=py37-dj21
    sudo: true  # TODO Remove when supported
    dist: xenial
    python: 3.7
  - env: TOX_ENV=py35-djmaster
    python: 3.5
  - env: TOX_ENV=py36-djmaster
    python: 3.6
  - env: TOX_ENV=py37-djmaster
    sudo: true  # TODO Remove when supported
    dist: xenial
    python: 3.7
  allow_failures:
  - env: TOX_ENV=py35-djmaster
  - env: TOX_ENV=py36-djmaster
  - env: TOX_ENV=py37-djmaster
install:
- pip install -U pip setuptools tox wheel
script:
- tox -e "${TOX_ENV}"
deploy:
  provider: pypi
  user: Surgo
  password:
    secure: ECQgP3QvjNyqe7sqeKMHOu4wAAvuDobweIGfHXMuWmLer7FKJeCb0HhuSNzZjXXCdTiE1km7dSaYU1Uvb0aA8Zi29oOS0oR4qPVKFibNSqnWrc8WnPhvSCnK9cT6CtwSpK48KYqENHfKbr1SAR2vTX8J3NhwRqBB0aS6bCYEKWU=
  distributions: sdist bdist_wheel
  on:
    repo: michaeljohnbarr/django-timezone-utils
    tags: true
    condition: "$TOX_ENV = py37-dj21"
notifications:
  email: false
